POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "adamDickhead",
  "name": "Adam Richard",
  "password": "richard_567",
  "gender": "male",
  "location": "Detroit"
}
###

POST http://localhost:3000/login---
Content-Type: application/json

{
  "username": "adamDickhead",
  "password": "richard_567"
}
###

PUT http://localhost:3000/change-password
Content-Type: application/json

{
  "username": "adamDickhead",
  "oldPassword": "sdfsdfsdfsf",
  "newPassword": "sdfsdfdafdafsdfsdf"
}

